### ISSUE TITLE
Exception('Could not find ECMA Script name')

### ISSUE THREAD

**Issue by hristiyanmarkov** [joqueka/bf4py#13]
When trying the example code
`from bf4py import BF4Py

from datetime import datetime, timedelta

bf4py = BF4Py(default_isin='DE0005190003')

bf4py.general.data_sheet_header() # Get info for BMW`

I get the following error:

`---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_19584\162570831.py in <module>
      2 from datetime import datetime, timedelta
      3 
----> 4 bf4py = BF4Py(default_isin='DE0005190003')
      5 
      6 bf4py.general.data_sheet_header() # Get info for BMW

~\anaconda3\lib\site-packages\bf4py\BF4Py.py in __init__(self, default_isin, default_mic)
     18         self.default_mic = default_mic
     19 
---> 20         self.connector = BF4PyConnector()
     21 
     22         self.equities = Equities(self.connector, self.default_isin)

~\anaconda3\lib\site-packages\bf4py\connector.py in __init__(self, salt)
     20             if len(file) != 1:
     21                 raise Exception('Could not find ECMA Script name')
---> 22 
     23             # Step 2: Get Javascript file and extract salt
     24             response = self.session.get('https://www.boerse-frankfurt.de/'+file[0])

Exception: Could not find ECMA Script name`

I managed to fix it by changing row 19 in connector.py from
`            file = re.findall('(?<=src=")main-es2015\.\w*\.js', response.text)` to
`            file = re.findall('(?<=src=")main\.\w*\.js', response.text)`

Not sure if it's a proper solution, but it works for now!

**Comment by joqueka** [comment]
Hi there,

thanks for that information. Your solution is absolutely correct, as they probably changed a file name due to an upgrade or whichever other reason. I just fixed the relevant file, let's see how long it will work ;)
