### ISSUE TITLE
live_quotes exceptions

### ISSUE THREAD

**Issue by schlummer13** [joqueka/bf4py#4]
This error comes up when calling the live_quotes function on Ubuntu 20.04. It works on Windows and Mac. Version: 3.10, 3.8

requests.exceptions.InvalidURL: Failed to parse: <Response [200]>

How can I solve this?

**Comment by joqueka** [comment]
This isn't enough information for me to get an idea where the error comes from. Maybe there's an issue when `urllib.parse.urlencode` is called to generate the URL. I can't test on Ubuntu, but you can play around with the code and try to find out why the URL is invalid.  If you can solve it feel free to make a pull request.

**Comment by schlummer13** [comment]
In Function _stream_request in _utils.py: 

socket = requests.get(url, stream=True, headers=header, timeout=(3.5, 5))
print(socket) #Output "<Response [200]>"
client = sseclient.SSEClient(socket)

But i wonder, why can Windows/Mac Python 3.10 use this and on Ubuntu Failed to Parse

**Comment by joqueka** [comment]
Maybe there's something wrong when Ubuntu is parsing the response. Response code 200 is actually fine and exactly what we want, didn't mention that in my first response. You can also try and remove timeout.

**Comment by schlummer13** [comment]
Also not works..

**Comment by joqueka** [comment]
Have a look this [post](https://stackoverflow.com/questions/61076294/how-to-handle-requests-exceptions-invalidurl-failed-to-parse-in-python) and try upgrading/downgrading urllib3. It's seems to be a similar issue. And please post some more of the error description if it keep failing.

**Comment by schlummer13** [comment]
Send me an E-Mail at hallo@somebot.de, so than we can easily talk :D

**Comment by joqueka** [comment]
Hi,
I just checked the package on a Debian System and Python 3.8 and it worked fine. I guess it's more a problem related to your specific system than to bugs in the bf4py package. If you find a solution elsewhere feel free to post it here.

**Comment by schlummer13** [comment]
Hi, yes it works now, it had to reset my server and reinstall everything. But i have remove the sseclient, and use requests.Session() as well. It works perfectly! :)

**Comment by Rolleg** [comment]
> 

Hi there! I have the same problem, can you please send the code with the use of requests.Session() ?

**Comment by schlummer13** [comment]
def _stream_request(params: dict):
    url = _get_data_url("quote_box", params)
    header = _create_header(url)
    header['accept'] = 'text/event-stream'
    header['cache-control'] = 'no-cache, no-store, must-revalidate, max-age=0'
    s = requests.Session()
    return s.get(url, stream=True, headers=header)

**Comment by schlummer13** [comment]
And in :

`def receive_data(self):`

replace:

`for event in self.client.events():
                if self.stop:
                    break
                if event.event == 'message':
                    try:
                        data = json.loads(event.data)
                        self.data.append(data)
                        if self.callback is not None:
                            self.callback(data)
                    except:
                        continue`

with:

`for line in self.client.iter_lines():
                if "data:" and "isin" in line.decode('utf-8'):
                    datas = json.loads(line.decode('utf-8').split("data:")[1])
                    #Infos = Aktie(a["bidLimit"], a["askLimit"], a["timestamp"].split("T")[1].split("+")[0])
                    if datas["timestamp"].split("T")[1].split("+")[0] != self.liste:
                        if datas["askLimit"] or datas["bidLimit"] != 0:
                            self.data = datas
                            print(self.data)
                            self.liste = datas["timestamp"].split("T")[1].split("+")[0]`

**Comment by Rolleg** [comment]
> And in :
> 
> `def receive_data(self):`
> 
> replace:
> 
> `for event in self.client.events():` `if self.stop:` ` break` ` if event.event == 'message':` `try:` `data = json.loads(event.data)` `self.data.append(data)` ` if self.callback is not None:` `self.callback(data)` `except:` `continue`
> 
> with:
> 
> `for line in self.client.iter_lines():` ` if "data:" and "isin" in line.decode('utf-8'):` `datas = json.loads(line.decode('utf-8').split("data:")[1])`
> 

Oh wow! No errors now, thank you! But the answer is still empty [] . For example in https://api.boerse-frankfurt.de/v1/data/quote_box?isin=DE0008404005&mic=XETR

**Comment by schlummer13** [comment]
The mic is: XFRA not XETR

**Comment by Rolleg** [comment]
> The mic is: XFRA not XETR
isin = 'US88160R1014'
mic = 'XFRA'
client = bf4py.live_data.live_quotes(isin,mic)
client.open_stream()
while True:
    time.sleep(3)
    print(client.data)
client.close()

Yes, I tried different ways, result is empty []

**Comment by schlummer13** [comment]
write me: info@somebot.de, i help you :D
