### ISSUE TITLE
It doesnt work anymore

### ISSUE THREAD

**Issue by schlummer13** [joqueka/bf4py#5]
The Statuscode ist 200, but the Body is empty.

**Comment by schlummer13** [comment]
Where do you get the salt?

**Comment by some-user123** [comment]
Try `w4ivc1ATTGta6njAZzMbkL3kJwxMfEAKDa3MNr`

**Comment by schlummer13** [comment]
it works, but where do you get this?

**Comment by schlummer13** [comment]
text me, if you can. I would you pay for this information. Discord: flofen, mail: hallo@somebot.de
