### ISSUE TITLE
AttributeError: module 'bf4py.live_data' has no attribute 'quote_box'

### ISSUE THREAD

**Issue by Rolleg** [joqueka/bf4py#7]
Hi there! For example to live data is such code:
For getting live data just create an receiver-client and start streaming:
client = bf4py.live_data.quote_box(isin)
client.open_stream()

But it returns an error:
AttributeError: module 'bf4py.live_data' has no attribute 'quote_box'
Maybe something was changed?

**Comment by joqueka** [comment]
Hi,
this was only a typo in the example!
client = bf4py.live_data.live_quotes(isin) 
is correct.
