### ISSUE TITLE
live feed not working

### ISSUE THREAD

**Issue by shrddr** [joqueka/bf4py#8]
steps: run code from README

```
isin = 'DE0008404005' # Allianz SE
bf4py.general.data_sheet_header(isin)
client = bf4py.live_data.live_quotes(isin)
client.open_stream()
```

error: `requests.exceptions.InvalidURL: Failed to parse: <Response [200]>`
inside https://github.com/joqueka/bf4py/blob/main/bf4py/_utils.py#L91

**Comment by joqueka** [comment]
Hi,
did you tried it again recently? I just tried it and it works on my machine, so I can't figure out what the problem was.
Cheers

**Comment by shrddr** [comment]
worked around by https://github.com/joqueka/bf4py/issues/4#issuecomment-1237246961
